// Productcatalogus. Pas namen, prijzen, kleuren en maten hier aan.
// "type" bepaalt welke mockup getekend wordt (zie mockups.js).
window.PG_CATEGORIES = [
  { id: "kleding", name: "Kleding", desc: "T-shirts, hoodies en sweaters" },
  { id: "accessoires", name: "Accessoires", desc: "Tassen, petten en meer" },
  { id: "wonen", name: "Wonen", desc: "Mokken, posters en kussens" },
  { id: "tech", name: "Tech", desc: "Telefoonhoesjes en muismatten" },
];

window.PG_PRODUCTS = [
  {
    id: "tshirt-classic",
    name: "Classic T-shirt",
    type: "tshirt",
    category: "kleding",
    price: 24.95,
    badge: "Bestseller",
    colors: ["#ffffff", "#111111", "#1f3a93", "#c0392b", "#7f8c8d", "#2e7d32"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    desc: "Zacht, 100% biologisch katoen (180 g/m²). Bedrukt met DTG voor heldere kleuren die wasbestendig zijn.",
  },
  {
    id: "hoodie-premium",
    name: "Premium Hoodie",
    type: "hoodie",
    category: "kleding",
    price: 49.95,
    badge: "Nieuw",
    colors: ["#111111", "#ffffff", "#7f8c8d", "#1b2a49", "#6d4c41"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    desc: "Dikke fleece hoodie (320 g/m²) met kangoeroezak en dubbele capuchon. Perfect voor jouw logo of ontwerp.",
  },
  {
    id: "sweater-crew",
    name: "Crewneck Sweater",
    type: "sweater",
    category: "kleding",
    price: 39.95,
    colors: ["#e8e0d5", "#111111", "#2e7d32", "#1f3a93"],
    sizes: ["S", "M", "L", "XL"],
    desc: "Tijdloze sweater met geborstelde binnenkant. Unisex pasvorm.",
  },
  {
    id: "mok-wit",
    name: "Keramische Mok 330 ml",
    type: "mug",
    category: "wonen",
    price: 14.95,
    badge: "Cadeautip",
    colors: ["#ffffff", "#111111"],
    sizes: ["330 ml"],
    desc: "Vaatwasser- en magnetronbestendig. Rondom bedrukt met jouw foto of tekst.",
  },
  {
    id: "poster-a3",
    name: "Poster Mat Papier",
    type: "poster",
    category: "wonen",
    price: 19.95,
    colors: ["#ffffff"],
    sizes: ["A4", "A3", "A2", "50×70"],
    sizePrices: { A4: 0, A3: 5, A2: 12, "50×70": 18 },
    desc: "Museumkwaliteit mat papier (200 g/m²). Scherpe details en diepe kleuren.",
  },
  {
    id: "kussen",
    name: "Sierkussen 45×45",
    type: "pillow",
    category: "wonen",
    price: 29.95,
    colors: ["#ffffff", "#e8e0d5"],
    sizes: ["45×45 cm"],
    desc: "Zachte polyester hoes inclusief vulling, rits aan de achterkant.",
  },
  {
    id: "tote-bag",
    name: "Katoenen Tote Bag",
    type: "tote",
    category: "accessoires",
    price: 16.95,
    colors: ["#e8e0d5", "#111111", "#ffffff"],
    sizes: ["One size"],
    desc: "Stevige katoenen tas (38×42 cm) met lange hengsels. Duurzaam alternatief voor plastic.",
  },
  {
    id: "pet",
    name: "Geborduurde Pet",
    type: "cap",
    category: "accessoires",
    price: 22.95,
    colors: ["#111111", "#ffffff", "#1b2a49", "#c0392b"],
    sizes: ["Verstelbaar"],
    desc: "Dad cap met verstelbare sluiting. Jouw logo wordt geborduurd.",
  },
  {
    id: "phonecase",
    name: "Telefoonhoesje",
    type: "phone",
    category: "tech",
    price: 19.95,
    colors: ["#ffffff", "#111111"],
    sizes: ["iPhone 16", "iPhone 16 Pro", "iPhone 15", "Galaxy S25", "Galaxy S24"],
    desc: "Slank, stevig hoesje met glanzende afwerking en volledige bedrukking.",
  },
  {
    id: "muismat",
    name: "Muismat",
    type: "mousepad",
    category: "tech",
    price: 12.95,
    colors: ["#ffffff"],
    sizes: ["Standaard", "XL"],
    sizePrices: { Standaard: 0, XL: 10 },
    desc: "Antislip rubberen onderkant en glad stoffen oppervlak voor precieze bewegingen.",
  },
];
